/*
Copyright 2017 The Stash Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package stash

import (
	apis_stash "github.com/appscode/stash/apis/stash"
	client "github.com/appscode/stash/client"
	internalinterfaces "github.com/appscode/stash/informers/externalversions/internalinterfaces"
	stash "github.com/appscode/stash/listers/apis/stash"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// ResticInformer provides access to a shared informer and lister for
// Restics.
type ResticInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() stash.ResticLister
}

type resticInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

func newResticInformer(client client.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	sharedIndexInformer := cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.ApisStash().Restics(v1.NamespaceAll).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.ApisStash().Restics(v1.NamespaceAll).Watch(options)
			},
		},
		&apis_stash.Restic{},
		resyncPeriod,
		cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc},
	)

	return sharedIndexInformer
}

func (f *resticInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apis_stash.Restic{}, newResticInformer)
}

func (f *resticInformer) Lister() stash.ResticLister {
	return stash.NewResticLister(f.Informer().GetIndexer())
}
